package dev.aurakai.auraframefx.aurakai.auraframefx.ai.model

// This file should be generated by OpenAPI generator from genesis-api.yml
// If this file is empty, the OpenAPI generation process needs to be run
// Run: ./gradlew generateAllConsciousnessApis
