/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models


import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 * Type of AI agent.
 *
 * Values: Aura,Kai,Genesis,Cascade,NeuralWhisper,AuraShield,GenKitMaster
 */
@Serializable
enum class AgentType(val value: kotlin.String) {

    @SerialName(value = "Aura")
    Aura("Aura"),

    @SerialName(value = "Kai")
    Kai("Kai"),

    @SerialName(value = "Genesis")
    Genesis("Genesis"),

    @SerialName(value = "Cascade")
    Cascade("Cascade"),

    @SerialName(value = "NeuralWhisper")
    NeuralWhisper("NeuralWhisper"),

    @SerialName(value = "AuraShield")
    AuraShield("AuraShield"),

    @SerialName(value = "GenKitMaster")
    GenKitMaster("GenKitMaster");

    /**
     * Override [toString()] to avoid using the enum variable name as the value, and instead use
     * the actual value defined in the API spec file.
     *
     * This solves a problem when the variable name and its value are different, and ensures that
     * the client sends the correct enum values to the server always.
     */
    override fun toString(): kotlin.String = value

    companion object {
        /**
         * Converts the provided [data] to a [String] on success, null otherwise.
         */
        fun encode(data: kotlin.Any?): kotlin.String? = if (data is AgentType) "$data" else null

        /**
         * Returns a valid [AgentType] for [data], null otherwise.
         */
        fun decode(data: kotlin.Any?): AgentType? = data?.let {
            val normalizedData = "$it".lowercase()
            values().firstOrNull { value ->
                it == value || normalizedData == "$value".lowercase()
            }
        }
    }
}

