/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package dev.aurakai.auraframefx.api.client.models

import kotlinx.serialization.Contextual
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 *
 * @param sender The AI agent that sent the message.
 * @param message The content of the message.
 * @param timestamp ISO 8601 timestamp of the message.
 */
@Serializable

data class AgentMessage(

    /* The AI agent that sent the message. */
    @Contextual @SerialName(value = "sender")
    val sender: AgentType,

    /* The content of the message. */
    @SerialName(value = "message")
    val message: kotlin.String,

    /* ISO 8601 timestamp of the message. */
    @Contextual @SerialName(value = "timestamp")
    val timestamp: java.time.OffsetDateTime,

    )

